"""scenarios table

Revision ID: 80a8f15aad48
Revises: 
Create Date: 2025-11-20 14:04:18.452401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a8f15aad48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_name', sa.String(length=64), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('data_source', sa.String(length=64), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenario_scenario_name'), ['scenario_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_scenario_timestamp'), ['timestamp'], unique=False)

    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_result_scenario_id'), ['scenario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_result_scenario_id'))

    op.drop_table('result')
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenario_timestamp'))
        batch_op.drop_index(batch_op.f('ix_scenario_scenario_name'))

    op.drop_table('scenario')
    # ### end Alembic commands ###
