"""first migration

Revision ID: c739c2d6f266
Revises: 
Create Date: 2025-12-19 10:55:43.808130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c739c2d6f266'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epc_abm_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uprn', sa.Integer(), nullable=False),
    sa.Column('lsoa_code', sa.String(), nullable=False),
    sa.Column('local_authority', sa.String(), nullable=False),
    sa.Column('ward_code', sa.String(), nullable=False),
    sa.Column('habitable_rooms', sa.Integer(), nullable=True),
    sa.Column('sap_rating', sa.Integer(), nullable=False),
    sa.Column('floor_area', sa.Float(), nullable=False),
    sa.Column('property_type', sa.String(), nullable=False),
    sa.Column('property_age', sa.String(), nullable=False),
    sa.Column('main_fuel', sa.String(), nullable=False),
    sa.Column('main_heating_system', sa.String(), nullable=False),
    sa.Column('sap_band_ord', sa.Integer(), nullable=False),
    sa.Column('retrofit_envelope_score', sa.Float(), nullable=False),
    sa.Column('is_off_gas', sa.Boolean(), nullable=True),
    sa.Column('energy_demand_kwh', sa.Float(), nullable=False),
    sa.Column('factor', sa.Float(), nullable=False),
    sa.Column('energy_cal_kwh', sa.Float(), nullable=False),
    sa.Column('heating_controls', sa.String(), nullable=True),
    sa.Column('meter_type', sa.String(), nullable=False),
    sa.Column('cwi_flag', sa.Boolean(), nullable=False),
    sa.Column('swi_flag', sa.Boolean(), nullable=False),
    sa.Column('loft_ins_flag', sa.Boolean(), nullable=False),
    sa.Column('floor_ins_flag', sa.Boolean(), nullable=False),
    sa.Column('glazing_flag', sa.Boolean(), nullable=False),
    sa.Column('is_electric_heating', sa.Boolean(), nullable=True),
    sa.Column('is_gas', sa.Boolean(), nullable=True),
    sa.Column('is_oil', sa.Boolean(), nullable=True),
    sa.Column('is_solid_fuel', sa.Boolean(), nullable=True),
    sa.Column('epc_lodgement_date_year', sa.Integer(), nullable=False),
    sa.Column('geometry', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_name', sa.String(length=64), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('data_source', sa.String(length=64), nullable=False),
    sa.Column('subset', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenario_scenario_name'), ['scenario_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_scenario_timestamp'), ['timestamp'], unique=False)

    op.create_table('temp_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset', sa.String(length=64), nullable=False),
    sa.Column('val1', sa.Float(), nullable=False),
    sa.Column('val2', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_time_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('energy_consumption', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('Agent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_time_series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_time_series_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('energy_time_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('total_energy', sa.Integer(), nullable=False),
    sa.Column('average_energy', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('energy_time_series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_energy_time_series_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('model_time_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('mid_terraced_house', sa.Float(), nullable=False),
    sa.Column('semi_detached_house', sa.Float(), nullable=False),
    sa.Column('flats_small', sa.Float(), nullable=False),
    sa.Column('flats_large', sa.Float(), nullable=False),
    sa.Column('flats_block', sa.Float(), nullable=False),
    sa.Column('end_terrace_house', sa.Float(), nullable=False),
    sa.Column('detached_house', sa.Float(), nullable=False),
    sa.Column('flat_mixed_use', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('medium', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('total_energy', sa.Float(), nullable=False),
    sa.Column('cumulative_energy', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_time_series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_time_series_scenario_id'), ['scenario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_time_series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_time_series_scenario_id'))

    op.drop_table('model_time_series')
    with op.batch_alter_table('energy_time_series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_energy_time_series_scenario_id'))

    op.drop_table('energy_time_series')
    with op.batch_alter_table('agent_time_series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_time_series_scenario_id'))

    op.drop_table('agent_time_series')
    op.drop_table('temp_table')
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenario_timestamp'))
        batch_op.drop_index(batch_op.f('ix_scenario_scenario_name'))

    op.drop_table('scenario')
    op.drop_table('epc_abm_data')
    # ### end Alembic commands ###
